// Package apidocs Code generated by swaggo/swag. DO NOT EDIT
package apidocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.HealthResponse"
                        }
                    }
                }
            }
        },
        "/openapi.json": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "docs"
                ],
                "summary": "OpenAPI spec",
                "responses": {
                    "200": {
                        "description": "OpenAPI JSON",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/conversions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversions"
                ],
                "summary": "List supported conversions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ConversionsResponse"
                        }
                    }
                }
            }
        },
        "/v1/convert": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversions"
                ],
                "summary": "Convert file",
                "parameters": [
                    {
                        "description": "Conversion request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.ConvertRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ConvertResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.ConversionsResponse": {
            "type": "object",
            "properties": {
                "formats": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "server.ConvertRequest": {
            "type": "object",
            "properties": {
                "contentBase64": {
                    "type": "string"
                },
                "fileName": {
                    "type": "string",
                    "example": "input.png"
                },
                "from": {
                    "type": "string",
                    "example": "png"
                },
                "to": {
                    "type": "string",
                    "example": "jpg"
                }
            }
        },
        "server.ConvertResponse": {
            "type": "object",
            "properties": {
                "contentBase64": {
                    "type": "string"
                },
                "fileName": {
                    "type": "string",
                    "example": "input.jpg"
                },
                "from": {
                    "type": "string",
                    "example": "png"
                },
                "mimeType": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "to": {
                    "type": "string",
                    "example": "jpg"
                }
            }
        },
        "server.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "unsupported_conversion_pair"
                },
                "message": {
                    "type": "string",
                    "example": "conversion from png to pdf is not supported"
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/server.ErrorDetail"
                }
            }
        },
        "server.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GoConverter API",
	Description:      "API for discovering available file conversions.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
